### ISSUE TITLE
spawning in modded dimensions that dont make sense (e.g. mars in ad astra)

### ISSUE THREAD

**Issue by MrKashew** [Legodamen/The-John-Mod-Reborn#2]
perhaps a config for dimensions/biomes?

**Comment by Legodamen** [comment]
Oof. That's not good. I thought I made them only be able to spawn in the overworld long ago. Thank you for letting me know. 700 Downloads and that's a problem. There will be a patch made soon. What version are you using?

**Comment by Legodamen** [comment]
It's fixed now in the newer version(s). For spawning in other biomes besides vanilla, will be for a different time. However, they now only spawn in the Overworld as intended.

**Comment by MrKashew** [comment]
Thanks so much!
