### ISSUE TITLE
Suggestion: Buff John, Break Shields / Knockback reduction

### ISSUE THREAD

**Issue by ConqAra** [Legodamen/The-John-Mod-Reborn#4]
Make John be able to break shields. John doesn''t have the same scary presence he once did in older versions due to just being able to hold the shield down. I think John and Mega John should both be able to just completely break your shield for a cooldown like brutes and vindicators do with their axes. Maybe reduce knockback too for john so you cant easily push him away either. Or at least a config option for it.

**Comment by Legodamen** [comment]
That's not a bad idea tbh, I write it down for this following update. 
Thanks for the suggestion!
