### ISSUE TITLE
Two Possible Mega John/The Hunted issues + Mega John buff idea

### ISSUE THREAD

**Issue by Daralexen05** [Legodamen/The-John-Mod-Reborn#5]
1. Mega John can still break leaves when Mob Griefing is turned off. Is this an intended feature or a bug?
2. The Hunted spawning issues. He did not show up until day 35 of my hardcore world, and two of them spawned close to each other in a small area.  Isn't he supposed to show up every night before a full moon?

Buff idea: Give Mega John a ranged attack to make him more worthy of his title as the boss of the mod and scarier. He is currently just a slow-moving hitbox that drops end-game resources and rewards. Maybe stomping the ground to cause shockwaves or shooting his bloody tears like Carmilla from Castlevania. The Bloody Tears would create an effect similar to the Ender Dragon's breath, but less deadly and it has a smaller pool of effect.

**Comment by Legodamen** [comment]
# Issue 1.
Just something i have not thought of. I will write that down tho :)
# Issue 2
he just spawns like every other mob. He's just rare so not too many spawn in one night. But this can lead to none spawning. However... I can add a guaranteed spawn for him. Also I can add a tick so 2 cant spawn next to each other like I did for the Ethereal John.

# Buff Idea
I do agree that he is not the most scary when taking in hind sight. I do got some plans, nothing ranged... maybe... I will see :) 

thanks, although, all these will be a 1.1 thing for me to add. so it will be a while.
