### ISSUE TITLE
Johns can spawn on Mycelium and in Mushroom Biomes

### ISSUE THREAD

**Issue by Daralexen05** [Legodamen/The-John-Mod-Reborn#6]
I went to a mushroom field at night, and I saw a lot of Johns, including five Mega Johns. This caused a lot of lag that caused my game to crash. Isn't the purpose and main gimmick of Mushroom Biomes that there are no other mobs except for Mooshrooms and no hostile mobs at night?

**Comment by Legodamen** [comment]
What version are you using of the mod? 
Game version, and mod version.

**Comment by Daralexen05** [comment]
> What version are you using of the mod? Game version, and mod version.

Minecraft 1.19.2 and version 1.0.5 of the mod, the latest release for 1.19.2. I think this is a problem not exclusive to John, I also saw Blood and Madness and Vampirism mobs spawn in the field, but it was still dominated primarily by Johns.

**Comment by Legodamen** [comment]
Ahhhh
Okay, so I believe how it works is that the biome doesn't make hostile mobs not spawn. They just don't spawn there via their coding. So I'll make it so they can no longer spawn in mooshroom islands. Or maybe just make it so they can only spawn in all "Minecraft" biomes expect certain ones. Cause now I'm curious about the deep dark too. 
Ill upload a patch later tonight, or tomorrow. Thanks for this. It will be for 1.19.2 only tho because of 1.1 development.

**Comment by Daralexen05** [comment]
> Ahhhh Okay, so I believe how it works is that the biome doesn't make hostile mobs not spawn. They just don't spawn there via their coding. So I'll make it so they can no longer spawn in mooshroom islands. Or maybe just make it so they can only spawn in all "Minecraft" biomes expect certain ones. Cause now I'm curious about the deep dark too. Ill upload a patch later tonight, or tomorrow. Thanks for this. It will be for 1.19.2 only tho because of 1.1 development.

I have seen John spawn in Deep Dark and in well-lit areas such as my base or a forest during the day. Him spawning in the daylight is not too annoying, since it might be a reference to older versions of the mod in which he could spawn in the day, but him in Deep Dark causes him to alert the Warden.

**Comment by Legodamen** [comment]
> > Ahhhh Okay, so I believe how it works is that the biome doesn't make hostile mobs not spawn. They just don't spawn there via their coding. So I'll make it so they can no longer spawn in mooshroom islands. Or maybe just make it so they can only spawn in all "Minecraft" biomes expect certain ones. Cause now I'm curious about the deep dark too. Ill upload a patch later tonight, or tomorrow. Thanks for this. It will be for 1.19.2 only tho because of 1.1 development.
> 
> I have seen John spawn in Deep Dark and in well-lit areas such as my base or a forest during the day. Him spawning in the daylight is not too annoying, since it might be a reference to older versions of the mod in which he could spawn in the day, but him in Deep Dark causes him to alert the Warden.

huh, spawning during the day? I have not had that before. have you changed any of the configs? And are you sure they spawned? And what type are spawning? Normal, Baby, The Hunted? And how "dark" is the areas?

**Comment by Daralexen05** [comment]
> > > Ahhhh Okay, so I believe how it works is that the biome doesn't make hostile mobs not spawn. They just don't spawn there via their coding. So I'll make it so they can no longer spawn in mooshroom islands. Or maybe just make it so they can only spawn in all "Minecraft" biomes expect certain ones. Cause now I'm curious about the deep dark too. Ill upload a patch later tonight, or tomorrow. Thanks for this. It will be for 1.19.2 only tho because of 1.1 development.
> > 
> > 
> > I have seen John spawn in Deep Dark and in well-lit areas such as my base or a forest during the day. Him spawning in the daylight is not too annoying, since it might be a reference to older versions of the mod in which he could spawn in the day, but him in Deep Dark causes him to alert the Warden.
> 
> huh, spawning during the day? I have not had that before. have you changed any of the configs? And are you sure they spawned? And what type are spawning? Normal, Baby, The Hunted? And how "dark" is the areas?

I did edit the config to disable all of the new John and Baby variants along with giving Mega John his classic spawn pattern. It is the normal John that I have seen spawn. I swear that John spawned inside my base once since I have a fence on the outside and he is three blocks tall, so he cannot enter my door. As for the forest incidents, maybe it was dark enough under trees for him to spawn, but I have seen no other hostile mobs from either vanilla or other mods spawn during the day aside from Pillagers. Maybe it can be a config option in later versions since he could rarely spawn in the day in the release 1.2 reboot of the mod

**Comment by Legodamen** [comment]
I was not able to find anything, but I will keep a open eye and mark it in my notes.
But I fixed the issue with the spawning in incorrect biomes in new update. Anything else comes up, feel free to open a Issue.
Thonks :)

https://www.curseforge.com/minecraft/mc-mods/the-john-mod-reborn/files/4956325
