### ISSUE TITLE
John and Baby John do not fight back when attacked by other mobs.

### ISSUE THREAD

**Issue by Daralexen05** [Legodamen/The-John-Mod-Reborn#7]
John and Baby John do not fight back against other mobs like Johnny Vindicators, Zoglins, Golems, Crocodiles from Alex's Mobs, Blood and Madness Huntsmen, or Doctors. I know that Baby John is programmed to avoid Iron Golems unless they are in a big enough group, but why do they just let single mobs beat them up? John is the original "Scariest mod" long before streamer bait like Cave Dweller, Man from the Fog, and Midnight Lurker, so this kind of takes away from the horror aspect of this mod.

**Comment by Legodamen** [comment]
This might have been a bug due to me constantly trying to fix the AI of the John's. 
what version of the mod and game version do you have?

**Comment by Daralexen05** [comment]
Version 1.19.2 and the latest release. This is also an issue in the latest release of the mod for 1.18.2. Mega John fights back against mobs that attack him like Zoglin Huntsmen though.

**Comment by Legodamen** [comment]
This is prob a bug from me constantly trying to fix the AI. However I won't really try to fix this until the 1.1 update, as It will be just easier to just off of from there. Because that update will more than make up for things.
