### ISSUE TITLE
Perennial Blade First-Person Texture is backwards

### ISSUE THREAD

**Issue by Braebro9k** [Legodamen/The-John-Mod-Reborn#9]
Extremely minor issue, just thought I'd bring it to your attention. The perennial blade texture is backwards in first-person view, curving forward instead of backward. Great mod btw!
![2023-12-18_21 09 26](https://github.com/Legodamen/The-John-Mod-Reborn/assets/154292500/b3ca496f-5d33-4518-bc51-6864764e6ae9)
![2023-12-18_21 10 26](https://github.com/Legodamen/The-John-Mod-Reborn/assets/154292500/412822e5-67c0-4c7c-aa3a-c5c1686bbd3e)

**Comment by Legodamen** [comment]
actually in 1st person its backwards. I did not even notice. But it will be fixed in the next updated :)
thank you
